docs: 优化 README 文件
Tianci-King/walk-view-2023 pull request #1
Opened 2024-10-02 10:14 UTC by xixiIBN5100

2024-10-02 10:36 UTC, j10ccc requested changes

2024-10-02 10:36 UTC, j10ccc commented on README.md
> +<a href="https://github.com/zjutjh/walk-view/graphs/contributors">
这个仓库是 `walk-front`，怎么连接到 `walk-view` 去了？

原来的老仓库可以 Archive 了

2024-10-02 10:36 UTC, j10ccc commented on README.md
> +本项目依赖于微信中的浏览器,并且不支持热重载,代码修改效果只能上传至服务器部署后在微信浏览器中查看
这个可以用点 ad-hoc 解决，没 HMR 这还怎么开发

2024-10-02 10:36 UTC, j10ccc commented on README.md
>  > **配置`/walk-view/src/config/Server.ts`**
这个文件名不对

2024-10-02 17:44 UTC, xixiIBN5100 commented on README.md
> +本项目依赖于微信中的浏览器,并且不支持热重载,代码修改效果只能上传至服务器部署后在微信浏览器中查看
找到解决方案了 后端配置一下localhost就可以了

2024-10-03 14:42 UTC, j10ccc approved these changes

2024-10-03 14:42 UTC, j10ccc commented on README.md
> +4. `pnpm run dev`点击url后打开浏览器后复制url到微信打开
这里写明白是电脑微信打开 `localhost:PORT`，局域网下其他设备打开的话还需要额外修改 vite dev server 的 web socket 请求地址，这里我们没做，所以开发环境下只能用开发机器上的微信打开

2024-10-03 15:25 UTC, merged

2024-10-03 15:28 UTC, j10ccc commented on README.md
> +4. `pnpm run dev`点击url后打开浏览器后复制url到微信打开
如果硬要普通浏览器打开，需要复制账号的 token，写到 localStorage 的 jwt 字段下 @xixiIBN5100

2024-10-03 15:38 UTC, xixiIBN5100 commented on README.md
> +4. `pnpm run dev`点击url后打开浏览器后复制url到微信打开
好的好的